### ISSUE TITLE
Behavior needed as a input for EOD schema lookups

### ISSUE THREAD

**Issue by flynngr** [imsweb/staging-algorithm-eod-public#12]
There are some EOD schemas (e.g. brain) that require behavior to differentiate, but the EODSchemaLookup doesn't allow behavior as an input key.  I could be missing something, as I'm new to working with the staging libraries.  I could get what I needed by using a generic SchemaLookup and including behavior as an input, but I thought I'd mention it.

**Comment by ctmay4** [comment]
The Brain schema does use behavior.  You can see the details here.

https://staging.seer.cancer.gov/eod_public/schema/1.7/brain/?breadcrumbs=(~schema_list~)

The `SchemaLookup` can use the `setInput` method to set other fields that are needed.

**Comment by ctmay4** [comment]
Can I close this issue or do you need more information?

**Comment by flynngr** [comment]
You can close.
