### ISSUE TITLE
Readme shows an example of a constructor that doesnt exist

### ISSUE THREAD

**Issue by isaackcr** [imsweb/staging-algorithm-eod-public#2]
In the Readme.md under "Lookup a schema", there is an example of a constructor with 3 arguments that does not exist, also, the example is for a TNM schema, not EOD: 

> // supply a discriminator
> lookup = staging.lookupSchema(new TnmSchemaLookup("C111", "8200", "010"));

**Comment by ctmay4** [comment]
Good catch.  I forgot to clean that up when I split the algorithms.  I just fixed it.

Thanks!
